### ISSUE TITLE
Setup custom LC styles

### ISSUE THREAD

**Issue by thatbudakguy** [WatzekDigitalInitiatives/geo.lclark.edu#3]
**in app/assets/stylesheets**
---
`application.css.scss`:

```scss
@import 'blacklight';
@import 'geoblacklight';
@import 'lclark';
```
`blacklight.scss`:

```scss
@import 'bootstrap-variables';
@import 'bootstrap-sprockets';
@import 'bootstrap';
@import 'blacklight/blacklight';
```
`bootstrap-variables.scss`:

```scss
$brand-primary: #e66b3f;
```
`geoblacklight.scss`:

```scss
@import 'geoblacklight/application';
```
`lclark.scss`:

```scss
@import 'modules/*';
```
**in app/assets/stylesheets/modules** (where new partials will go)
---
`_header.scss`:

```scss
// Add a custom logo to the header

#header-navbar {
  .navbar-brand {
    // background: 
  }
}
```
`_icon.scss`:

```scss
// Color L&C's icon and adjust its position

.geoblacklight-lewis-clark {
  &::before {
    color: $brand-primary;
    margin-right: -3px;
    padding-left: 3px;
  }
}
// Remove default coloration from Stanford's

.geoblacklight-stanford {
  &::before {
    color: $gray-light;
  }
}

```
