### ISSUE TITLE
Change homepage display text

### ISSUE THREAD

**Issue by thatbudakguy** [WatzekDigitalInitiatives/geo.lclark.edu#7]
**`config/locales/geoblacklight.en.yml`**

```yml
en:
  geoblacklight:
    home:
      headline: 'Find maps and data'
      search_heading: 'Get started here'
      category_heading: 'Browse by category'
      map_heading: 'Browse by location'
```
