### ISSUE TITLE
Set institution-specific configs

### ISSUE THREAD

**Issue by thatbudakguy** [WatzekDigitalInitiatives/geo.lclark.edu#9]
**`config/settings.yml`**

```yml
# Institution deployed at
INSTITUTION: 'Lewis & Clark'
```

**`config/locales/blacklight.en.yml`**

```yml
en:
  blacklight:
    application_name: 'geo.lclark'
```
